### ISSUE TITLE
AI git commit/push 能否改为将暂存区内容进行 commit/push

### ISSUE THREAD

**Issue by rofixro** [mefengl/vscode-i-dont-care-about-commit-message#14]
感谢作者开源如此好用的工具👍

**Comment by mefengl** [comment]
谢谢~

想要的效果是什么呢？自己手动`git add`，然后基于这些改变去 commit/push 吗？

这其实是个很好的问题，我之前有思考过。

有很多 ai commit 工具的确是这样的，我之前使用这些工具的时候就会觉得，这个步骤太慢了，还是要到终端去击键。

我觉得比较妥协的方式可以是：
![image](https://github.com/mefengl/vscode-i-dont-care-about-commit-message/assets/71683364/76eca2ce-02e8-4f39-9bf9-32432f882206)

但感觉还是工作流的问题，如果可以改变工作流，比如每做一些改变就及时提交，这样就可以省去`git add`的时间。我是信奉“如果思考是否commit的时间已经可以提交一次commit，就提交吧”，在绑定了快捷键之后尤其如此。至于commit可能会看起来过多的问题，其实也可以通过 pr 的 `Squash and merge` 去合并。

你有什么想法吗？

**Comment by rofixro** [comment]
我跟你的想法一样，也是喜欢写一点就去提交代码。但是也有可能会遇到写了很多，暂时只会提交某一部分的情况。相对终端来说，我基本是在 IDE 里面提交代码，我会先手动选择要提交的代码存入缓冲区，然后执行 AI git push，觉得也挺方便的。对于多个文件只选择一部分进行提交，这个步骤不管是终端还是 IDE 都是需要手动确认的，剩下的可以交给 AI 去处理。你在图中展示的列表是待提交的文件列表吗？如果是的话这一步我可以在 IDE 就完成了。

**Comment by mefengl** [comment]
@niyaco 嘿！现在预览版插件可以提交暂存区文件了。

至于之前说的“比较妥协的方式”还在开发中。我也看了别的插件的实现，它们很多会在 VS Code 的版本管理的页面里加上按钮，我觉得这样很不优雅，因为那里存在着修改 commit message 的可能，其实还是会有人类确认的负担。

有什么好的建议欢迎说呀～

**Comment by mefengl** [comment]
<img width="638" alt="image" src="https://github.com/mefengl/vscode-i-dont-care-about-commit-message/assets/71683364/3327ac8e-ee0c-46d1-8ac4-48e2ff25c435">
