### ISSUE TITLE
[Feature Request] Support limiting the number of characters in commit content

### ISSUE THREAD

**Issue by lainbo** [mefengl/vscode-i-dont-care-about-commit-message#19]
Sometimes the generated content is too long. VSCode recommends commit messages to be no more than 50 characters. Maybe we can limit it or add an option to adjust the generated text

**Comment by mefengl** [comment]
This problem may be reduced a lot by setting the `conventional commit` option on:
![image](https://github.com/mefengl/vscode-i-dont-care-about-commit-message/assets/71683364/42012bd1-dac8-4f96-9eff-0bf87aa6f063)

And I may also explore some better ways to prompt

**Comment by lainbo** [comment]
> This problem may be reduced a lot by setting the `conventional commit` option on: ![image](https://user-images.githubusercontent.com/71683364/254213716-42012bd1-dac8-4f96-9eff-0bf87aa6f063.png)
> 
> And I may also explore some better ways to prompt

Thank you, I will give it a try. Regarding this issue, I have come up with a not-so-good solution. It involves setting a word limit in the prompt for GPT and checking the word count after receiving the response. If it exceeds the set limit, another request will be sent to make the GPT response more concise, until it meets the word requirement. Of course, this will result in longer response times and more token consumption. I hope there is a better solution

**Comment by mefengl** [comment]
Yep, you know what? I tried a similar solution, but not with the length; I auto-reply it with [commitlint](https://github.com/conventional-changelog/commitlint) error msg, and it doesn't work well, at least for gpt-3.5.

This is quite a heavy solution for now, cause there is no very good framework for this.

Adding one more follow-up prompt "shorter" should also be enough, but just like you said "this will result in longer response times and more token consumption", it may not be worth it.

So I may add the keyword "concise" to the prompt. After all, "I Don't Care About Commit Message" :)
