### ISSUE TITLE
fatal: ambiguous argument ':!yarn.lock': unknown revision or path not in the working tree

### ISSUE THREAD

**Issue by ghost** [mefengl/vscode-i-dont-care-about-commit-message#7]
```
fatal: ambiguous argument ':!yarn.lock': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

https://github.com/mefengl/vscode-i-dont-care-about-commit-message/assets/106857035/ee64c333-6db7-455c-ae33-c359e2f3cf9b

**Comment by mefengl** [comment]
@zjy4fun Run `git -v` to check the version to see if it's above the `3.23.0`.

**Comment by mefengl** [comment]
Should fix this by https://github.com/mefengl/vscode-i-dont-care-about-commit-message/commit/1214d255b54365c525158e61e19986a922225792

Update the plugin to see if it works for you
